### ISSUE TITLE
Remove dist from archive_from_source excludes

### ISSUE THREAD

**Issue by TimothyBJacobs** [cedaro/satispress#100]
We ship a plugin that includes a `dist` directory in the plugin root that contains the built version of our JS files.

https://github.com/cedaro/satispress/blob/af03db0e153945cee2c00f90498ebf0e5e200e73/src/Archiver.php#L75

The `dist` directory is intentionally removed. I can see why the other directory names are excluded as they are dev files, but isn't `dist` usually for built files that are necessary for the plugin to run?

**Comment by bradyvercher** [comment]
`/dist` is where all of my themes and plugins compile and save the release artifact for distribution. I'm not totally opposed to removing it from the default excludes if I'm the only one using it for that.

**Comment by TimothyBJacobs** [comment]
Ah, interesting.

Would maybe supporting `.distignore` work? https://developer.wordpress.org/cli/commands/dist-archive/

**Comment by bradyvercher** [comment]
Yeah, that would probably work and would be easier to use than the filter.
