### ISSUE TITLE
Can't whitelist plugins after filtering

### ISSUE THREAD

**Issue by pawelkmpt** [cedaro/satispress#107]
Plugins are not added to whitelist if ones filters the list.

**Steps to reproduce**

1. Filter plugins by name using _Search installed plugins..._ field
2. Click checkbox on the list of filtered plugins

**Result**

* AJAX request is not triggered and plugin is not whitelisted
* Clearing search field does not help, page reload is needed

**Comment by lkraav** [comment]
Yep, confirmed, experienced the same thing.

**Comment by bradyvercher** [comment]
Thanks for reporting this, @pawelkmpt. I'm pretty sure 9d5f60f should fix this, but let me know if not.
