### ISSUE TITLE
Activating WPML breaks satispress authentication

### ISSUE THREAD

**Issue by xama5** [cedaro/satispress#111]
# Description of the issue

After enabling the Plugin "WPML Multilingual CMS", composer is unable to authenticate itself with satispress. By trying to access https://APIKEY:satispress@domain.tld/satispress/packages.json a WP error is displayed: Sorry, you cannot view this resource. (gray site with text in a white box)

# Steps to reproduce the issue

1) Install the paid version (premium) of WPML Multilingual CMS and enable it
2) Set up license and enable automatic updates
3) Check the Satispress checkbox in the plugins overview

It appears that it doesn't matter whether the Satispress checkbox is ticked or not. It breaks immediately after enabling WPML. When I disable WPML, Satispress works fine again.

**Comment by bradyvercher** [comment]
Unfortunately, I don't have access to WPML or a license to update automatic updates, so this isn't something I can look into. In any case, it sounds the issue is with WPML, so your best bet is to reach out to their support and let them know about the conflict. Thanks!
