### ISSUE TITLE
New releases for private repos

### ISSUE THREAD

**Issue by minemindmedia** [cedaro/satispress#113]
Hi, I have some custom plugins we've developed on github and we're using Satispress as a central package server.

Trying to figure out how Satispress recognizes new releases from Github. We've created a new release for a plugin but Satispress doesn't appear to see it?

**Comment by bradyvercher** [comment]
Hi @minemindmedia, SatisPress doesn't handle updates itself and doesn't provide any integration with GitHub. It's designed to allow third-party plugins that you don't have control over to be managed with Composer (they do need to deliver their updates through the WordPress update process).

There are usually ways to manage code that you control with Composer without having to use SatisPress/WordPress as a proxy. However, if you're really wanting to make your custom plugin updates available through SatisPress, you might look into using [GitHub Updater](https://github.com/afragen/github-updater) by @afragen.
