### ISSUE TITLE
Transfer API-keys from 0.3.2 to 0.5.0

### ISSUE THREAD

**Issue by koenHuybrechts** [cedaro/satispress#114]
We have a SatisPress installation version 0.3.2 in production. I'm upgrading to 0.5.0 and move the repository to a new server. Where can I find the API-keys, generated in the old installation (0.3.2), please? So I can migrate all keys.
If I'm right, the newest version generates a usermeta record?
For example: satispress_api_key.RANDOMKEY

**Comment by bradyvercher** [comment]
Yep, API Keys are [saved to user meta](https://github.com/cedaro/satispress/blob/491710a56e4140e5654fd68e400940b4fb589110/src/Authentication/ApiKey/Repository.php#L131-L135). You can run a SQL query like this to find them:

```sql
SELECT * FROM wp_usermeta WHERE meta_key LIKE 'satispress_api_key.%';
```
