### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by binaryfire** [cedaro/satispress#120]
Hey @bradyvercher 

Would love to see a git integration option! Eg. pushing plugins to private git repos along with an auto generated composer.json file. New updates would be pushed as tags.

**Comment by bradyvercher** [comment]
@binaryfire Thanks for the suggestion! I've considered something like that in the past and it should be possible to write an adapter that uses git as a storage layer, but it's not something I have immediate plans to add. Let me know if you're interested in giving it a shot and I can try to point you in the right direction.
