### ISSUE TITLE
Get packages list via REST API

### ISSUE THREAD

**Issue by binaryfire** [cedaro/satispress#121]
Any chance of adding a REST API endpoint to list all available packages along with the available version numbers? Basically a way to get this info as json: https://github.com/cedaro/satispress/blob/develop/docs/packages.md

**Comment by bradyvercher** [comment]
I wrote several endpoints to manage themes, plugins, and packages for a commercial alternative I was working on a couple years ago called [Crate](https://cratewp.com/), but don't currently have a need for something like that in SatisPress.

It should be fairly easy to write an add-on to either add a custom endpoint similar to `/satispress/packages.json` or register a read-only REST API endpoint to output that data.

**Comment by therajumandapati** [comment]
@bradyvercher Has the work stopped on Crate?

**Comment by bradyvercher** [comment]
@therajumandapati We have discontinued work on Crate. I still really like the concept and think it has potential, but there didn't seem to be enough interest. Some of the improvements made their way into SatisPress with the 0.3 rewrite, though.
