### ISSUE TITLE
Changelog archive per plugin?

### ISSUE THREAD

**Issue by matthijsdewit** [cedaro/satispress#125]
Hello there,

Many plugins come with a changelog when new versions are released, is there a way to preserve/store this with Satispress?

Thanks,

Matthijs

**Comment by bradyvercher** [comment]
That's a new idea and could be interesting, but there's not a way to do it at the moment. Are plugins only showing changes for the most recent version? If I recall correctly, there isn't really a standardized format for the changelog -- it's just a blob of HTML. Surfacing a URL somewhere in the admin could be a nice benefit, too.
