### ISSUE TITLE
PHP Warning: tmpfname too long in Archiver.php

### ISSUE THREAD

**Issue by BrianHenryIE** [cedaro/satispress#128]
I got this after installing SatisPress on a site and trying to make the theme available:
```
PHP Warning:  rename(/tmp/bAd80mxr7v23rgh01xswxkfsr35g49cdjyy25nspmvhA9sssmngxg8c3nr52mt6gknhwAAdgjjb25s6lkbjf176jg8dxk76p48cs9t6t48gx47rtkv3Akwrtjnhwyn6q4r225m6nlfvw2ql3pb7vsndbjzrgsA5nkrlhs56A4zkAmvsdmr2fmzllkfmg5AkhnvAfmtcmkrgd1m5nnjA274dl3nggsn65gzn2mytk4rbAc5lckA6g2szqlb1s9rswljvAcm5ngzjxcvk4l29q-8kqxes.tmp,/tmp/satispress/flatsome-3.11.0.zip): File name too long in /path/to/wp-content/plugins/satispress/src/Archiver.php on line 177
```

[Archiver.php:177](https://github.com/cedaro/satispress/blob/develop/src/Archiver.php#L177) is `if ( ! rename( $tmpfname, $filename ) ) {` where `$tmpfname` comes from WordPress's own `download_url()` from [wp_tempnam()](https://github.com/WordPress/wordpress-develop/blob/936b65887c5ac8f6a411d4f817bf53a11524630c/src/wp-admin/includes/file.php#L633-L678).

The package was available to download before I noticed the log.

**Comment by bradyvercher** [comment]
Thanks for the report, @BrianHenryIE. Is there something here that needs to be fixed or accounted for in SatisPress? Or is that an upstream issue with `wp_tempname()`?

**Comment by BrianHenryIE** [comment]
Yeah, seems to be upstream. I didn't put a huge effort into investigating, at the time I just wanted it noted. I'll take a look at WordPress Trac.
