### ISSUE TITLE
Having issues with downloading files on 'composer update'

### ISSUE THREAD

**Issue by patrickmceldowney** [cedaro/satispress#136]
```
[Composer\Downloader\TransportException]                      
  The "https://pluginsite.com/?satispress_route=compo  
  ser/packages.json" file could not be downloaded (HTTP/2 500)
```

The API keys are all working because I'm not getting an authentication errors. The plugin is a WooCommerce extension and it is correctly whitelisted on the donor site. This site is also built on Bedrock and Trellis. I'm not entirely sure on where to go from here, does anyone have any recommendations on what to try next?

Here's my auth.json
```
{
  "http-basic": {
    "pluginsite.com": {
        "username": "{%SATISPRESS_API_KEY}",
        "password": "{%SATISPRESS_PSWD}"
    }
  }
}
```
And here's my composer.json
```
 {
    "type": "composer",
    "url": "https://pluginsite.com/?satispress_route=composer"
}
```

```
{
    "require": {
          "satispress/woocommerce-product-filters": "1.2.3"
     }
}
```

**Comment by bradyvercher** [comment]
@patrickmceldowney Did you ever figure out what was going here? It looks like you probably need to check the error logs on your server to see what's causing that 500 error.
