### ISSUE TITLE
Incompatible with Composer 2.0

### ISSUE THREAD

**Issue by aaronware** [cedaro/satispress#139]
**Issue:** Recently updated a project to utilize composer 2 via `php-actions/composer@v5` it looks like
`dealerdirect/phpcodesniffer-composer-installer` `v0.5^` is not compatible with composer 2.

**Resolution:** `dealerdirect/phpcodesniffer-composer-installer` added Composer 2 compatibility in release v0.7.0

Updating to version 0.7.1 appeared to work in my initial tests.

I'm going to create a quick pull request for you to review, let me know if you need anything else for a merge

**Comment by bradyvercher** [comment]
Thanks @aaronware! This has been merged. I also wasn't sure how to get in touch directly, but really appreciate the donation a few days ago. Every little bit helps 😄

**Comment by aaronware** [comment]
No problem @bradyvercher! It's a great plugin and was super helpful in getting our setup going
