### ISSUE TITLE
users with satispress_view_packages capability can't access packages list in admin

### ISSUE THREAD

**Issue by mihkeleidast** [cedaro/satispress#146]
I added `satispress_download_packages` and `satispress_view_packages` capabilities to "Subscriber" role. This added the "SatisPress API Keys" section to the subscribers profile page. But there's no way for those users to see what packages/versions are actually available other than inspecting the packages.json file.

I would expect users with those two capabilites to have access to the "Packages" tab in the SatisPress settings page so they could see what packages are available with what versions and could download the packages from the admin UI.

**Comment by bradyvercher** [comment]
I could go either way on this. That's a settings screen and other roles usually don't see that menu item. It was primarily added as a convenience for admins and wasn't really intended as an interface for other users. I can see how making it available to members of a team would be useful, though.

**Comment by mihkeleidast** [comment]
I guess what I'm looking for is a UI (a la https://packagist.org/) so team members could search/filter/download packages and their older versions. Does not have to be that specific Settings page, maybe some other place? I guess the alternative would be to build a "theme" that would offer that functionality? I like my current SatisPress site though because it's basically only WP + Plugins and I did not need to configure anything else (basically running in headless mode).

**Comment by bradyvercher** [comment]
A theme could be cool, or even a shortcode/block add-on that could be embedded in any theme.

I'll close this for now, but if anyone else is interested in something similar, please feel free to chime in. Also, let me know if you build out a theme, @mihkeleidast. I'd be interested in seeing it.

**Comment by mihkeleidast** [comment]
Yeah, but that would be a quite large undertaking. Wouldn't it be a lot simpler to in the meantime make that packages tab visible to users with correct rights? Or split it to a separate page maybe?
