### ISSUE TITLE
administrators do not see entire list of added access keys

### ISSUE THREAD

**Issue by mihkeleidast** [cedaro/satispress#147]
The current logic seems to be that all access keys are defined under the user's profile. Administrators who have access to the SatisPress settings page, only see their own access keys on that settings page. I would expect that list to include all access keys for all users, because it's a global settins page.

Some context, too: if trying to find out which user's access key has been "a bad boy" (downloading too much or been shared with people who should not have access to the repository), the only way to find out which user's key it is, is to go through all users profiles. This can be quite cumbersome when there are a lot of users.

Also, a "revoke all" button would be nice :)

**Comment by bradyvercher** [comment]
Thanks for the feedback, @mihkeleidast. I admit there is lots of room for improvement, potential for new features, and alternative use cases that could be explored. As much as I'd like to be able to tackle those various challenges, it does take up a lot of time to build, test, maintain, and support. My main goal for now is to keep this focused on making themes and plugins available to Composer. It should be extensible enough that add-ons could be built to serve your particular needs, though.

As for the API keys on the settings screen, those are there to make setup quick and easy for the majority of people that try SatisPress out, so they don't have to hunt for various options to get started.

I imagine if you're able to track how often a package is downloaded or whether a key has been shared, it'll probably be trivial to hunt down which user it belongs to 😄
