### ISSUE TITLE
Fatal error when viewing wp plugin list

### ISSUE THREAD

**Issue by alapiere** [cedaro/satispress#148]
Hi, 
After installing a plugin on satispress server installation, 
It crashes when viewing plugin list. My guess is the extension is faulty
I cannont deactivate the faulty extension, due to this.
Of course I can fire up a DB access, deactivate manually the faulty plugin, and it will probably fix the issue.
But it would be nice to catch it , handle error gracefully, and give some more expltipsanations about the faulty plugin.

`Fatal error: Uncaught TypeError: Argument 1 passed to SatisPress\Exception\InvalidPackageArtifact::containsMacOsxDirectory() must be of the type string, null given, called in /www/wpcontroljengo_729/public/wp-content/plugins/satispress/src/Validator/HiddenDirectoryValidator.php on line 38 and defined in /www/wpcontroljengo_729/public/wp-content/plugins/satispress/src/Exception/InvalidPackageArtifact.php:50 Stack trace: #0 /www/wpcontroljengo_729/public/wp-content/plugins/satispress/src/Validator/HiddenDirectoryValidator.php(38): SatisPress\Exception\InvalidPackageArtifact::containsMacOsxDirectory(NULL) #1 /www/wpcontroljengo_729/public/wp-content/plugins/satispress/src/Archiver.php(221): SatisPress\Validator\HiddenDirectoryValidator->validate('/tmp/download-H...', Object(SatisPress\Release)) #2 /www/wpcontroljengo_729/public/wp-content/plugins/satispress/src/ReleaseManager.php(91): SatisPress\Archiver->archive_from_url(Object(SatisPress\Release)) #3 /www/wpcontroljengo_729/public/wp-content/plugins/satispress/src/Provider in /www/wpcontroljengo_729/public/wp-content/plugins/satispress/src/Exception/InvalidPackageArtifact.php on line 50`

**Comment by bradyvercher** [comment]
This one looks like it was a bug, but it should be fixed in 2801e2b.

**Comment by alapiere** [comment]
confirmed, not bug after update. 
thanks !
