### ISSUE TITLE
Plugins whitelisted by default

### ISSUE THREAD

**Issue by LucasDemea** [cedaro/satispress#154]
Hi,
Is there a way to enabled satispress by default for each new installed plugin ?

**Comment by bradyvercher** [comment]
There isn't a setting for that, but you could replace the whitelist repository with the plugins repository. You wouldn't be able to remove plugins going this route, though.

```php
add_action( 'satispress_compose', function( $plugin, $container ) {
	$container['repository.whitelist'] = $container['repository.plugins'];
}, 10, 2 );
```

**Comment by LucasDemea** [comment]
Thank you, it could do the job in my. Otherwise is there a wp filter or something that could be a starting point to add this feature by code ?

**Comment by bradyvercher** [comment]
You can create your own repository with your own rules and replace it in the same way. Or use the [satispress_plugins](https://github.com/cedaro/satispress/blob/06678c7cd6fa5f16767d5d5e4f301383d12f0547/src/ServiceProvider.php#L249) filter. The whitelist repository actually starts with all installed plugins and themes and filters out ones that haven't been enabled.

**Comment by LucasDemea** [comment]
Thanks, will have a look at that !

**Comment by LucasDemea** [comment]
Just for reference, I ended up adding a mu-plugin with :
```php
function satispress_plugin_filter() {
	return array_keys( get_plugins() );
}

add_filter( 'satispress_plugins', 'satispress_plugin_filter' );
```
This way, all newly added plugin are automatically activated by satispress.
