### ISSUE TITLE
Compatibility with PHP 8

### ISSUE THREAD

**Issue by adisetiawan** [cedaro/satispress#155]
during `composer update`

```
Problem 1
    - Root composer.json requires cedaro/satispress ^1.0.0 -> satisfiable by cedaro/satispress[v1.0.0].
    - cedaro/satispress v1.0.0 requires php ^7 -> your php version (8.0.3) does not satisfy that requirement.
  ```

proposed solution:
update composer.json `"php": ">=7.1",`

**Comment by bradyvercher** [comment]
I haven't tested SatisPress with PHP 8, so can't make any guarantees it works without issue. If someone wants to test it and report back whether or not it works, I can make that update.

**Comment by raphaelparent** [comment]
@bradyvercher #165 seems to be related to PHP 8.0. I have downgraded to 7.4 and everything is working as expected.

**Comment by raphaelparent** [comment]
Same for #164

**Comment by acalvino4** [comment]
And #166, which really is #165 with a different error message as the title.
