### ISSUE TITLE
Weird menu placement on 1.0.0

### ISSUE THREAD

**Issue by patrick-leb** [cedaro/satispress#156]
The button to manage is on top:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/68301566/113452972-17b43280-93d3-11eb-990e-3837bf792d78.png">

But the window appears at the bottom:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/68301566/113452888-f5221980-93d2-11eb-9869-587e5121feb6.png">

I'm not sure if it was intended or something is wrong on my end :)

**Comment by bradyvercher** [comment]
Nope, that's not intended! That should open as a sidebar over on the right side (there's a [screenshot in the docs here](https://github.com/cedaro/satispress/blob/develop/docs/setup.md)). Can you try it in a different browser?

**Comment by patrick-leb** [comment]
It works in Chrome! I can't remember the last time I had something work in chrome but not in Safari. There are no console warnings or anything on Safari

---

It was caching issue. 🤦

I will just go back to the hole I crawled out from...!

Apologies for that stupid ticket!
