### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '===' (T_IS_IDENTICAL) in /var/www/wordpress/web/app/plugins/satispress/src/Integration/EnvatoMarket.php on line 78

### ISSUE THREAD

**Issue by dakhran** [cedaro/satispress#159]
When I upload and activate the plugin [Envato Market](https://envato.com/market-plugin/), the site becomes nonfunctional, and I receive the PHP parse error above.

SatisPress version: 1.0.1
nginx version: nginx/1.18.0 (Ubuntu)
PHP version: PHP 7.4.3

**Comment by dakhran** [comment]
Just wanted to add, it looks like a simple parenthesis issue, I was able to update the line to the following and get it to work:

`if ( (int) $item['id'] === (int) $id ) {`

**Comment by bradyvercher** [comment]
@dakhran Thanks for the report and tracking down the issue! I've pushed a fix for this and will get it out in the next release.

**Comment by pixelbrad** [comment]
@bradyvercher Any ETA on that release? Just dealt with this bug on my repo site.
