### ISSUE TITLE
Could not find a matching version of package

### ISSUE THREAD

**Issue by campaignupgrade** [cedaro/satispress#170]
`composer require satispress/wp-all-import-pro`

Result: 

```
[InvalidArgumentException]
  Could not find a matching version of package satispress/wp-all-import-pro. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).
 ```
 

-  The spelling is correct and is copied from the Satispress Repository tab
-  I've tried this with and without various version tags
-  minimum stability is dev
-  A dozen other plugins are working correctly
-  The plugins are managed by satispress 
-  wp-all-import-pro is listed in the Repositories tab
-  wp-all-import-pro is listed in https://plugins.mysite.org/satispress/packages.json
 - the json validates 
-  I can download the plugin at https://plugins.mysite.org/satispress/wp-all-import-pro/4.7.1
-  Other packages at satispress that are not in the project can be added to the project
-  Only this package is failing 
-  `composer show satispress/advanced-ads-pro` works
- `composer show satispress/wp-all-import-pro` fails, "[InvalidArgumentException] Package satispress/wp-all-import-pro not found"
-  I'm using an http header to authenticate if that matters 
```
        "satispress": {
            "type": "composer",
            "url": "https://plugins.mysite.org/satispress/",
            "options":  {
              "http": {
                "header": [
                  "API-TOKEN:  -----------------"
                ]
              }
            }
          },
          ```
            
Any ideas what's going on?

**Comment by bradyvercher** [comment]
@campaignupgrade Sorry, I really don't have any ideas. It sounds like you covered everything I would have tried. Were you able to figure this out?

**Comment by campaignupgrade** [comment]
I never figured it out.

Two days later I ran it again and it's working fine. I had made no changes to my configuration. 

This issue can be closed until I can make the issue repeatable.

**Comment by campaignupgrade** [comment]
Does Satispress store a _local_ copy of which packages are available on a remote repo?

**Comment by bradyvercher** [comment]
@campaignupgrade Thanks for the update.

SatisPress stores a local copy of new releases as WordPress becomes aware of them. It doesn't deal with any remote repos except to download and cache new releases. Communication with remotes is still handled through the WordPress update API, SatisPress just hooks into the process to create the local repo.
