### ISSUE TITLE
Satispress settings vanished

### ISSUE THREAD

**Issue by badabingbreda** [cedaro/satispress#175]
I seem to have an issue where my Satispress settings screen isn't registering. It has vanished and I can't really tell when that started because the plugin seems to work fine when I call it using Composer on my old machine. I only noticed because I got a new machine and need to make the initial connection.

I've disabled all plugins but Satispress, switched theme to "Twenty Twenty-Two". There's nothing in functions.php, I removed MU-plugin WP Object Cache) to make sure that everything is as vanilla as possibly can. It's running WP 5.9, PHP 7.4.

I tried reaching the page directly by entering it in the browser ( /wp-admin/options-general.php?page=satispress ) but I'm "not allowed to access that page" although I'm the only user and an admin.

I'm really at a loss here, would hate to rebuild my repo.

**Comment by bradyvercher** [comment]
It sounds like you might not have the [necessary capability](https://github.com/cedaro/satispress/blob/develop/docs/security.md#capabilities) to view the settings screen. You might try installing the [Members](https://wordpress.org/plugins/members/) plugin and make sure you have the `satispress_manage_options` capability.  You don't need to keep that plugin active after enabling the capability for your user.

**Comment by badabingbreda** [comment]
@bradyvercher Thank you so much for looking into this and responding so quickly. Your solution was spot on, installed MemberPress, went into the administrator role, SatisPress tab on the left, and I had no rights whatsoever. Three easy clicks and an update and it was solved. This saves me tons of work.

**Comment by bradyvercher** [comment]
Awesome, glad to hear that worked! And thank you so much for the contribution!
