### ISSUE TITLE
strtolower() expects parameter 1 to be string, int given

### ISSUE THREAD

**Issue by saas786** [cedaro/satispress#192]
![chrome_RvJO6uROT0](https://user-images.githubusercontent.com/1642796/196880120-e3707a72-6ad3-4d3f-8113-1c9b0880fbe7.png)

Ref: https://github.com/cedaro/satispress/blob/v1.0.4/src/functions.php#L84

**Comment by bradyvercher** [comment]
@saas786 Do you know what the header values being processed are and why one of them is an integer?

**Comment by saas786** [comment]
> @saas786 Do you know what the header values being processed are and why one of them is an integer?

I don't know the exact header, but I can share the sequence of stack trace.

---

![step-1-chrome_5KhijMjNIP](https://user-images.githubusercontent.com/1642796/200234306-20ceb91d-7d7a-428f-a238-6205bc980a43.png)

---

![step-2-rhO4icezjL](https://user-images.githubusercontent.com/1642796/200234328-799e1f01-366d-43d7-9644-ffa810ae4616.png)

---

![step-3-chrome_jQyMA08pzz](https://user-images.githubusercontent.com/1642796/200234486-08ccd067-dee4-4009-ab2f-dfe64790e157.png)

---

![step-4-chrome_WeRxKqQeCw](https://user-images.githubusercontent.com/1642796/200234501-20e8dde9-6ad5-4289-9e57-46a76d33d2bd.png)

---

![step-5-chrome_YwuWeEIdvk](https://user-images.githubusercontent.com/1642796/200234525-3f8a241b-4df3-4b02-aabc-7814321d90aa.png)

---

![step-6-chrome_QQVdeseYJf](https://user-images.githubusercontent.com/1642796/200234555-4fad1b0a-bf4b-40ac-bc9b-5b3555dc2408.png)

---

![step-7-chrome_CntcihsnXT](https://user-images.githubusercontent.com/1642796/200234576-d71e6408-2f20-482d-9c87-d97df53a010f.png)
