### ISSUE TITLE
curl error 92 while downloading

### ISSUE THREAD

**Issue by LucasDemea** [cedaro/satispress#194]
Could be related to #193 but I'm not sure.

I get this error from `composer require` or `composer update` :

```console
https://my-domain.com/satispress could not be fully loaded (curl error 92 while downloading https://my-domain.com/satispress/packages.json: HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)), package information was loaded from the local cache and may be out of date
```

The problem appeared with the upgrade to ubuntu 22.10 and the new new cURL version that comes with it. If I downgrade cURL, the problem goes away (tried the 7.70.0 version). I also tried to download satispress package.json using only cURL (not composer), and the problem is the same, which means the issue doesn't come from composer but  from cURL.

[cURL now forces HTTP/2 when connecting to https url](https://curl.se/docs/http2.html), and this causes the failure when the server doesn't provide an up to date API.

Curl version and modules:
`curl 7.85.0 (x86_64-pc-linux-gnu) libcurl/7.85.0 OpenSSL/3.0.5 zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.49.0 librtmp/2.3`

**Comment by bradyvercher** [comment]
Hi @LucasDemea, do you know if this is related to something SatisPress is doing? Or is it a server configuration issue? Are you able to access any resources from the default WordPress REST API?

**Comment by LucasDemea** [comment]
Just tested a simple wp rest api request, and the problem is the same. I guess the issue doesn't come from satispress.
Closing this, thanks
