### ISSUE TITLE
Bump / confirm min PHP version

### ISSUE THREAD

**Issue by GaryJones** [cedaro/satispress#198]
The docs say that PHP 7.0 is the minimum, but the composer.json file says >=7.1.

The nature of the plugin means it's aimed at a technical audience, so while I would ordinarily say 7.1 is a good minimum (some nice strongly-typed features available), we could make this even later - 7.3 would mean only needing to use PHPUnit 9, for instance.

@bradyvercher Thoughts?

**Comment by bradyvercher** [comment]
I bumped this to 8.0 in the latest version. It can likely be bumped again in the future, but I wanted to start there without having time for further testing.
