### ISSUE TITLE
Fatal errors on version 2.0.0

### ISSUE THREAD

**Issue by g000m** [cedaro/satispress#215]
Satispress auto-updated and is erroring

`
Fatal error: Uncaught Error: Class "Psr\Log\AbstractLogger" not found in /var/www/releases/1337/wp-content/plugins/satispress/src/Logger.php:27 Stack trace: #0 /var/www/releases/1337/wp-content/plugins/git-updater/vendor/composer/ClassLoader.php(576): include() #1 /var/www/releases/1337/wp-content/plugins/git-updater/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}() #2 /var/www/releases/1337/wp-content/plugins/satispress/src/ServiceProvider.php(177): Composer\Autoload\ClassLoader->loadClass() #3 /var/www/releases/1337/wp-content/plugins/satispress/vendor/pimple/pimple/src/Pimple/Container.php(122): SatisPress\ServiceProvider->SatisPress\{closure}() #4 /var/www/releases/1337/wp-content/plugins/satispress/src/ServiceProvider.php(60): Pimple\Container->offsetGet() #5 /var/www/releases/1337/wp-content/plugins/satispress/vendor/pimple/pimple/src/Pimple/Container.php(122): SatisPress\ServiceProvider->SatisPress\{closure}() #6 /var/www/releases/1337/wp-content/plugins/satispress/src/ServiceProvider.php(206): Pimple\Container->offsetGet() #7 /var/www/releases/1337/wp-content/plugins/satispress/vendor/pimple/pimple/src/Pimple/Container.php(122): SatisPress\ServiceProvider->SatisPress\{closure}() #8 /var/www/releases/1337/wp-content/plugins/satispress/src/ServiceProvider.php(191): Pimple\Container->offsetGet() #9 /var/www/releases/1337/wp-content/plugins/satispress/vendor/pimple/pimple/src/Pimple/Container.php(122): SatisPress\ServiceProvider->SatisPress\{closure}() #10 /var/www/releases/1337/wp-content/plugins/satispress/src/ServiceProvider.php(222): Pimple\Container->offsetGet() #11 /var/www/releases/1337/wp-content/plugins/satispress/vendor/pimple/pimple/src/Pimple/Container.php(122): SatisPress\ServiceProvider->SatisPress\{closure}() #12 /var/www/releases/1337/wp-content/plugins/satispress/src/ServiceProvider.php(213): Pimple\Container->offsetGet() #13 /var/www/releases/1337/wp-content/plugins/satispress/vendor/pimple/pimple/src/Pimple/Container.php(122): SatisPress\ServiceProvider->SatisPress\{closure}() #14 /var/www/releases/1337/wp-content/plugins/satispress/src/ServiceProvider.php(125): Pimple\Container->offsetGet() #15 /var/www/releases/1337/wp-content/plugins/satispress/vendor/pimple/pimple/src/Pimple/Container.php(122): SatisPress\ServiceProvider->SatisPress\{closure}() #16 /var/www/releases/1337/wp-content/plugins/satispress/src/Container.php(34): Pimple\Container->offsetGet() #17 /var/www/releases/1337/wp-content/plugins/satispress/src/Plugin.php(50): SatisPress\Container->get() #18 /var/www/releases/1337/wp-includes/class-wp-hook.php(324): SatisPress\Plugin->compose() #19 /var/www/releases/1337/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #20 /var/www/releases/1337/wp-includes/plugin.php(517): WP_Hook->do_action() #21 /var/www/releases/1337/wp-settings.php(555): do_action() #22 /var/www/releases/1337/wp-config.php(107): require_once('/var/www/_wp1.g...') #23 /var/www/releases/1337/wp-load.php(50): require_once('/var/www/_wp1.g...') #24 /var/www/releases/1337/wp-blog-header.php(13): require_once('/var/www/_wp1.g...') #25 /var/www/releases/1337/index.php(17): require('/var/www/_wp1.g...') #26 {main} thrown in /var/www/releases/1337/wp-content/plugins/satispress/src/Logger.php on line 27
`

**Comment by bradyvercher** [comment]
How did SatisPress auto-update? I'm assuming it might be an issue with missing dependencies in the release artifact I uploaded, but I don't have access to a computer right now to check.

**Comment by g000m** [comment]
Via git-updater

**Comment by g000m** [comment]
I just reinstalled it from the repo, ran composer install and it's working.

**Comment by g000m** [comment]
But I'd reinstalled from the release zip a couple of times and kept getting the error

**Comment by bradyvercher** [comment]
@g000m Thanks for checking that. I updated the release zip to include the missing dependency, so it should work now.
