### ISSUE TITLE
External Storage Options

### ISSUE THREAD

**Issue by aaronware** [cedaro/satispress#216]
In issue #134 there is some work related to offloading plugins to S3, I was going to use @bradyvercher's example as a starting point as a base for creating a Cloudflare r2 implementation since their library has support for the S3 APIs so the approach should be very similar. Just wondering if that is still a good base example since satispress recently had a 2.0 release so I wasn't sure if the architecture for implementing this was still the best approach.

**Comment by bradyvercher** [comment]
@aaronware The latest release mostly had some minor PHP compatibility and dependency updates. There weren't any major architecture changes, so that's still a good starting point. Your adapter just needs to implement the [storage interface](https://github.com/cedaro/satispress/blob/develop/src/Storage/Storage.php).

**Comment by aaronware** [comment]
Had some time to play with this over the holiday. The Storage interface example from #134 is just about 💯 just one minor adjustment for anyone else looking to do this in the future. @bradyvercher thanks for the shove in the right direction.

For any one implementing something similar, if you look at how Storage/Local is implemented it will give you insight into the change and then just follow the defined interface.

```
/**
 * Hook into SatisPress to register the R2 adapter.
 */
add_action( 'satispress_compose', function( $satispress, $container ) {
	$container['storage.packages'] = new R2_Adapter(); // use storage.packages not just storage
}, 10, 2 );
```

Going to consider this one closed

**Comment by aaronware** [comment]
Just a note on this. If you have plugins that are remotely hosted in my case Cloudflare R2 , it may be more worth storing a transient for the packages in list_files() especially if you have a lot of plugins and versions (in our case 100+ plugins each with 1-30 versions) so extraneous calls aren't needed looking for packages for an extra level of caching. Just clear the cache when installing other plugins or adding plugins to the managed packages.
