### ISSUE TITLE
mu-plugin support

### ISSUE THREAD

**Issue by joldnl** [cedaro/satispress#24]
I have a must use plugin installed. My composer.json has this content:

`{
    "name": "pms72/pms72-soil",
    "homepage": "https://bitbucket.org/pms72/pms72-soil",
    "authors": [
        {
            "name"      : "Jurgen Oldenburg",
            "email"     : "jurgen@pms72.com",
            "homepage"  : "http://www.pms72.com"
        }
    ],
    "type": "wordpress-muplugin",
    "require": {
        "composer/installers": "~1.0"
    }
}
`

Unfortunately, satispress does not pick up the type from the composer file, but sets it statically, so the plugin is placed in the standard plugins folder, in stead of the mu-plugins folder. Can this be fixed?

**Comment by bradyvercher** [comment]
I'm not quite sure what the benefit of SatisPress is for mu-plugins since they can't be installed or updated without manually moving files. Is there a reason you can't load that package [as a VCS repository](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository) in your project's `composer.json` instead?

**Comment by joldnl** [comment]
Yes. We use satispress to manage our private wordpress plugins, that are used in our Bedrock based wordpress installs, and we have some must-use plugins that our wordpress theme relies on. Satis does pick up the 'type' field from the plugin composer.json file, but satispress does not.

**Comment by GaryJones** [comment]
It's possible that updating [`get_whitelist()`](https://github.com/blazersix/satispress/blob/b792d29529a8f5036822c1a94f392a646aabb8aa/includes/class-satispress.php#L221-L236) and [`get_package()`](https://github.com/blazersix/satispress/blob/b792d29529a8f5036822c1a94f392a646aabb8aa/includes/class-satispress.php#L170-L174) with a new class (extend our plugin class, but change the `get_type()` hard-coded return value) might be a better way to go. You can then filter a new mu-plugin whitelist filter (or add a UI like the normal Plugins screen has), instead of adding in non-standard Plugin Headers to mu-plugins that might not be under your team's control.

**Comment by bradyvercher** [comment]
My thinking is that this is a problem already solved by Composer. Anyone that's able to add a custom header likely already has access to the VCS repository and can add it directly to the end-project's `composer.json`.

If someone doesn't have access to the VCS repository, then there could be a valid use case, but it would require manually updating the plugin for each release, which can be done just as easily by checking each release into a "forked" repo.

I'm still not sold it's a good idea to add support, but if so, these are the proposed options I've seen so far:

* Check the `type` field in the plugin's `composer.json` if it exists
* Introducing a new class and manually whitelist the mu-plugins
* Use a custom plugin header

I think I'd prefer the first option as the easiest way to solve this. The second would allow for manual overrides if necessary.

**Comment by bradyvercher** [comment]
There are multiple ways this can be handled, so I think it would probably work better as an add-on. Using the latest version of SatisPress, something like this would check for a `composer.json` file in the package and use the type defined there:

```php
<?php
use SatisPress\Package;
use SatisPress\Transformer\ComposerPackageTransformer;

add_action( 'satispress_compose', function( $plugin, $container ) {
	$container['transformer.composer_package'] = function( $container ) {
		return new class( $container['package.factory'] ) extends ComposerPackageTransformer {
			public function transform( Package $package ) {
				$package = parent::transform( $package );

				if ( $package->is_installed() && file_exists( $package->get_path( 'composer.json' ) ) ) {
					$builder = $this->factory->create( 'composer' )->with_package( $package );
					$json    = json_decode( file_get_contents( $package->get_path( 'composer.json' ) ) );
					$package = $builder->set_type( $json->type )->build();
				}

				return $package;
			}
		};
	};
}, 10, 2 );
```

If this is something anyone else needs, let me know and I can look into cleaning that up a bit and creating the add-on.

**Comment by cjkoepke** [comment]
I definitely could use support to `mu-plugins`.

**Comment by bradyvercher** [comment]
@cjkoepke Can you share more about what would be ideal for you?

* Are you using SatisPress in production or as a dedicated package repository?
* How are you planning in updating mu-plugins?
* What do is the benefit over adding the VCS repository in `composer.json`?

**Comment by cjkoepke** [comment]
Sure!

- Not sure what you mean, but I'm using it as an external dedicated package repository for both local and production websites.
- via Composer
- That's actually a good question. I can certainly just use a GitHub repository — it's just I would have to manually create releases as far as I know, and versions are automatically created in SatisPress.

**Comment by thefrosty** [comment]
Going to jump in here to see if this helps, @joldnl you can force a package in composer to be installed in any location by defining additional params in the _installer-path_, try something like this:

```
"extra": {
    "installer-paths": {
      "wp-content/mu-plugins/{$name}/": [
        "type:wordpress-muplugin",
        "cedaro/satispress"
      ],
    }
  },
```

By defining `cedaro/satispress` in the installer-path of mu-plugins, you can then force the install into your must use directory. Hope that helps.
