### ISSUE TITLE
Move to new GitHub organization

### ISSUE THREAD

**Issue by bradyvercher** [cedaro/satispress#71]
I'm planning on moving this repo to the Cedaro GitHub organization to make it easier to track and provide more visibility since the Blazer Six GitHub organization isn't active. This issue is to document that change and any steps users might need to take to make the switch.

**Comment by bradyvercher** [comment]
Based on the [comments in this issue](https://github.com/composer/packagist/issues/47#issuecomment-271962248), these are the steps needed to rename a package on packagist.org:

* Move to Cedaro organization on GitHub
* Update references and URLs to the old repository location (GitHub should handle redirects automatically)
* Change the package name to `cedaro/satispress` in `composer.json`
* Submit `cedaro/satispress` as a new package on packagist.org
* Mark `blazersix/satispress` as abandoned on packagist.org

## For Developers

Any projects that require SatisPress in `composer.json` will need to update the package name from `blazersix/satispress` to `cedaro/satispress`. Composer should display a notification that the old package is abandoned and suggest switching to the alternative.

**Comment by GaryJones** [comment]
> Mark blazersix/satispress as abandoned on packagist.org

To be more explicit, IIRC, when you mark it as abandoned, you have the option of saying what the replacement package is.

Also, for Contributors, we can update the `origin` remote for our local git repos :-)

For posterity, the current root namespace is `SatisPress` (just the package name, no vendor), so nothing would need to change here.

**Comment by bradyvercher** [comment]
> I take it GH couldn't help with giving us the @SatisPress organisation?

Unfortunately, no. They said it didn't quality as dormant, but did reach out on my behalf. It's been a few weeks without a response, so I figured that was no longer an option.

**Comment by bradyvercher** [comment]
This has now been switched over to Cedaro and Packagist has been updated.
