### ISSUE TITLE
Group packages by customer/project to manage individual authentications

### ISSUE THREAD

**Issue by tyrann0us** [cedaro/satispress#78]
Hi,
we are currently investigating whether this package meets our requirements of handling premium (not publicly available) packages.

One issue we see is that once you are authenticated you get access to all packages. But often different developers/teams need access to different "groups" of packages (e. g. grouped by customer/project).

AFAIS there are two meta capability called `satispress_download_package` and `satispress_view_package` but no built-in features to easily create and manage such groups and their authentications via UI or CLI.

Do you have any plans to implement this?
Thanks!

**Comment by bradyvercher** [comment]
Hi @tyrann0us, those capabilities were added to make something like that possible, but I don't have immediate plans to implement support for multiple repositories.

If you're interested in sponsoring an add-on, @GaryJones or myself might be available to help out with that.

**Comment by bradyvercher** [comment]
I'm going to close this out, but let me know if you do pursue it. I'm happy to promote anything you come up with in the readme 😃
