### ISSUE TITLE
How to add old plugin versions

### ISSUE THREAD

**Issue by koenHuybrechts** [cedaro/satispress#80]
We have an "old" Satispress version, but with the new release we redid the whole setup.
At the moment, there are 200+ plugins hosted by our Satispress install.

When adding the 200+ packages, only the newest version will be hosted by Satispress.
In our old install, we had a lot of older versions and for some websites, we only can have an older version of the plugin installed. For example from Gravity Forms.

How can I add older versions of packages?

**Comment by bradyvercher** [comment]
In that case, you just need to copy the artifacts from the old `/wp-content/uploads/satispress` directory to the new `/wp-content/uploads/satispress-{xxxx}/packages` directory. rsync would probably be the easiest route.

How is performance on a setup with that many plugins?

**Comment by bradyvercher** [comment]
I'm going to go ahead and close this out, but let me know if you had any problems migrating cached packages.

**Comment by koenHuybrechts** [comment]
Thanks @bradyvercher for your reply!

I tried this already on the 13th of September.
As you can see on the first screenshot, I have some older versions of Gravity Forms:
<img width="255" alt="screen shot 2018-09-27 at 22 07 14" src="https://user-images.githubusercontent.com/617708/46171766-d098d400-c2a1-11e8-8da6-34a0d263ecc5.png">

These are the versions recognised by Satispress:

<img width="484" alt="screen shot 2018-09-27 at 22 07 30" src="https://user-images.githubusercontent.com/617708/46171767-d098d400-c2a1-11e8-85a6-57a7315b687f.png">

Any idea how/where I can see or find our what went wrong?

**Comment by bradyvercher** [comment]
Are those in the `/wp-content/uploads/satispress-xxxx/packages/gravityforms/` directory? The location changed since the previous version, so it's import to make sure the cache directory has the random suffix and that the artifacts are in the `/packages` subdirectory.

**Comment by koenHuybrechts** [comment]
Ah! The subdirectory /packages was not there!
This was the missing link for my understanding.
Thanks!
