### ISSUE TITLE
Overwriting Existing .htaccess Rules

### ISSUE THREAD

**Issue by leepeterson** [cedaro/satispress#84]
When the "pretty permalinks" option is enabled, SatisPress overwrites the typical Apache rewrite rules for WordPress in .htaccess, adding `RewriteRule ^satispress/packages.json$ /index.php?satispress_route=composer [QSA,L]`.

I understand why this happens, and it's a nice convenience for sure. 

However, if that block of rules has been modified in any way, those modifications are lost without warning.

To provide an understanding of why this is an issue for us, we always modify that block in a way that works and ensures WordPress will not overwrite it later by simply keeping the changes in between `# BEGIN WordPress` and `# END WordPress`. It also makes for a much cleaner, smaller .htaccess file.

**Comment by bradyvercher** [comment]
@leepeterson Were you able to look into this further or is there anything else I can help with?

**Comment by leepeterson** [comment]
Apologies for the late response. 

I see that I failed to provide a solution. All I was getting at is that it’d be good to mention that this will occur. 

Just caught me by surprise :)
