### ISSUE TITLE
Debugging a package that won't appear in 'packages.json'

### ISSUE THREAD

**Issue by danielbachhuber** [cedaro/satispress#92]
We're using SatisPress to serve Restrict Content Pro. RCP has a beta3 version that's visible in the backend:

![image](https://user-images.githubusercontent.com/36432/53204479-95949580-35e0-11e9-81b6-fb1b9aa1d810.png)

However, the beta3 version doesn't appear in `packages.json`

![image](https://user-images.githubusercontent.com/36432/53204474-8f061e00-35e0-11e9-8581-283549f73be4.png)

What's the best way to debug this situation? Thanks in advance!

**Comment by danielbachhuber** [comment]
Chatted with Brady in Slack. My specific issue was that the artifact hadn't been created for 3.0.0-beta-3 (a bug for SatisPress <0.3.2). Clicking the "Download" button created the artifact and fixed my issue:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/36432/53205623-ad214d80-35e3-11e9-82dc-8b54a56c5f7b.png">

**Comment by TimothyBJacobs** [comment]
I experienced this issue on `0.5.0`. Manually doing the download fixed the issue as well.

**Comment by bradyvercher** [comment]
@TimothyBJacobs Just-in-time caching for the win! Do you have any idea why it didn't cache automatically, though?
